export enum NotificationType {
  STUDENT_REQUEST_CREATED = 'STUDENT_REQUEST_CREATED',
  /** Asignación de docente (envío diferido ~1 min). */
  STUDENT_PROFESSOR_ASSIGNED = 'STUDENT_PROFESSOR_ASSIGNED',
  STUDENT_PROFESSOR_CONFIRMED = 'STUDENT_PROFESSOR_CONFIRMED',
  STUDENT_REMINDER_3D = 'STUDENT_REMINDER_3D',
  STUDENT_REMINDER_1D = 'STUDENT_REMINDER_1D',
  STUDENT_REMINDER_1H = 'STUDENT_REMINDER_1H',
  PROFESSOR_SESSION_ASSIGNED = 'PROFESSOR_SESSION_ASSIGNED',
  PROFESSOR_REMINDER_3D = 'PROFESSOR_REMINDER_3D',
  PROFESSOR_REMINDER_1D = 'PROFESSOR_REMINDER_1D',
  PROFESSOR_REMINDER_1H = 'PROFESSOR_REMINDER_1H',
  ADMIN_MANUAL_ASSIGNMENT = 'ADMIN_MANUAL_ASSIGNMENT',
}
